/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Johan Pindeville (https://sketchfab.com/johanpindeville)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/viking-fisherman-house-009e0fdee2d2499e9596c2115d7a9ae3
Title: Viking fisherman house
*/

import React, { useRef,useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame,useThree } from "@react-three/fiber";
import Islandscene from '../assets/public/viking_fisherman_house.glb';
import { a } from '@react-spring/three'
const Island=({ isRotating, setIsRotating, setCurrentStage, ...props})=> {
  const islandRef=useRef();
  const { gl , viewport }  =useThree();

  const lastX=useRef(0);
  const rotationspeed=useRef(0);
  const dampingfactor=0.95;
  const handlePointerDown=(e)=>{
    e.stopPropagation();
    e.preventDefault();
    setIsRotating(true);
    const clientX =e.touches ? e.touches[0] : e.clientX;

    lastX.current= clientX;
  }
  const handlePointerUp=(e)=>{
    e.stopPropagation();
    e.preventDefault();
    setIsRotating(false);
    

  }
  const handlePointerMove=(e)=>{
    e.stopPropagation();
    e.preventDefault();

    if(isRotating){
      const clientX =e.touches ? e.touches[0] : e.clientX;

    const delta =(clientX - lastX.current) /viewport.width;
    islandRef.current.rotation.y+=delta*0.01*Math.PI;

    lastX.current=clientX;
    rotationspeed.current =delta* 0.01*Math.PI
    }
  }

  useFrame(()=>{
    if(!isRotating){
      rotationspeed.current*=dampingfactor;
      if(Math.abs(rotationspeed.current)==0.001){
        rotationspeed.current=0;
      }

      islandRef.current.rotation.y+=rotationspeed.current;
    }
    else{
      const rotation=islandRef.current.rotation.y;
      const normalizedRotation =
        ((rotation % (2 * Math.PI)) + 2 * Math.PI) % (2 * Math.PI);

      // Set the current stage based on the island's orientation
      switch (true) {
        case normalizedRotation >= 3.45 && normalizedRotation <= 4.00:
          setCurrentStage(4);
          break;
        case normalizedRotation >= 0.85 && normalizedRotation <= 1.3:
          setCurrentStage(3);
          break;
        case normalizedRotation >= 2.2 && normalizedRotation <= 3.0:
          setCurrentStage(2);
          break;
        case normalizedRotation >= 5.00 && normalizedRotation <= 5.75:
          setCurrentStage(1);
          break;
        default:
          setCurrentStage(null);
      }
    }
  })

  useEffect(()=>{
    const canvas=gl.domElement;
    canvas.addEventListener('pointerdown',handlePointerDown);
    canvas.addEventListener('pointerup',handlePointerUp);
    canvas.addEventListener('pointermove',handlePointerMove);
    return()=>{
      canvas.removeEventListener('pointerdown',handlePointerDown);
      canvas.removeEventListener('pointerup',handlePointerUp);
      canvas.removeEventListener('pointermove',handlePointerMove);
    }

  },[gl,handlePointerDown,handlePointerMove,handlePointerUp])
  const { nodes, materials } = useGLTF(Islandscene);
  return (
    <a.group ref={islandRef} {...props} >
      <mesh
        
        
        geometry={nodes.pCylinder55_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.pCylinder54_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.polySurface1346_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.polySurface1363_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.pPlane128_envi_texture_0.geometry}
        material={materials.envi_texture}
      />
      <mesh
        
        
        geometry={nodes.polySurface5562_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.pTorus6_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.polySurface5508_envi_texture_0.geometry}
        material={materials.envi_texture}
      />
      <mesh
        
        
        geometry={nodes.polySurface5520_envi_texture_0.geometry}
        material={materials.envi_texture}
      />
      <mesh
        
        
        geometry={nodes.polySurface4870_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.pPlane104_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.pPlane104_lambert10_0.geometry}
        material={materials.lambert10}
      />
      <mesh
        
        
        geometry={nodes.polySurface5439_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.pTorus5_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.pPlane100_envi_texture_0.geometry}
        material={materials.envi_texture}
      />
      <mesh
        
        
        geometry={nodes.polySurface1329_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.polySurface1330_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.polySurface1333_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.polySurface5445_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.polySurface5484_envi_texture_0.geometry}
        material={materials.envi_texture}
      />
      <mesh
        
        
        geometry={nodes.polySurface5404_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.polySurface3283_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.polySurface5389_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.polySurface5403_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.polySurface4531_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.pSphere6_envi_texture_0.geometry}
        material={materials.envi_texture}
      />
      <mesh
        
        
        geometry={nodes.polySurface4892_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.polySurface4408_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.polySurface4409_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.polySurface4078_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.pSphere8_envi_texture_0.geometry}
        material={materials.envi_texture}
      />
      <mesh
        
        
        geometry={nodes.polySurface4304_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.polySurface3858_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.polySurface4490_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.polySurface4520_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.polySurface4521_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.pSphere15_envi_texture_0.geometry}
        material={materials.envi_texture}
      />
      <mesh
        
        
        geometry={nodes.pCube215_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.pCube216_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.pCube214_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.polySurface4873_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.polySurface4871_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.polySurface5521_envi_texture_0.geometry}
        material={materials.envi_texture}
      />
      <mesh
        
        
        geometry={nodes.pCylinder122_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.pSphere11_envi_texture_0.geometry}
        material={materials.envi_texture}
      />
      <mesh
        
        
        geometry={nodes.pSphere14_envi_texture_0.geometry}
        material={materials.envi_texture}
      />
      <mesh
        
        
        geometry={nodes.pSphere10_envi_texture_0.geometry}
        material={materials.envi_texture}
      />
      <mesh
        
        
        geometry={nodes.pSphere9_envi_texture_0.geometry}
        material={materials.envi_texture}
      />
      <mesh
        
        
        geometry={nodes.pCylinder44_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.polySurface4406_lambert1_0.geometry}
        material={materials.lambert1}
      />
      <mesh
        
        
        geometry={nodes.polySurface1350_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.polySurface4489_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.polySurface4411_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.polySurface3908_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.pPlane76_envi_texture_0.geometry}
        material={materials.envi_texture}
      />
      <mesh
        
        
        geometry={nodes.polySurface3238_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.polySurface3686_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.polySurface3453_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.polySurface4017_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.pSphere12_envi_texture_0.geometry}
        material={materials.envi_texture}
      />
      <mesh
        
        
        geometry={nodes.pSphere13_envi_texture_0.geometry}
        material={materials.envi_texture}
      />
      <mesh
        
        
        geometry={nodes.pSphere16_envi_texture_0.geometry}
        material={materials.envi_texture}
      />
      <mesh
        
        
        geometry={nodes.polySurface3543_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.polySurface3730_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.pSphere7_envi_texture_0.geometry}
        material={materials.envi_texture}
      />
      <mesh
        
        
        geometry={nodes.polySurface3412_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.polySurface3839_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.pPlane64_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.polySurface4024_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.pSphere17_envi_texture_0.geometry}
        material={materials.envi_texture}
      />
      <mesh
        
        
        geometry={nodes.polySurface4868_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.pPlane1_envi_texture_0.geometry}
        material={materials.envi_texture}
      />
      <mesh
        
        
        geometry={nodes.pPlane2_envi_texture_0.geometry}
        material={materials.envi_texture}
      />
      <mesh
        
        
        geometry={nodes.pSphere19_envi_texture_0.geometry}
        material={materials.envi_texture}
      />
      <mesh
        
        
        geometry={nodes.pSphere18_envi_texture_0.geometry}
        material={materials.envi_texture}
      />
      <mesh
        
        
        geometry={nodes.pSphere20_envi_texture_0.geometry}
        material={materials.envi_texture}
      />
      <mesh
        
        
        geometry={nodes.pSphere21_envi_texture_0.geometry}
        material={materials.envi_texture}
      />
      <mesh
        
        
        geometry={nodes.pCylinder56_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.polySurface3977_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.polySurface5279_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.polySurface5035_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.polySurface3366_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.polySurface3540_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.polySurface3352_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.polySurface3362_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.polySurface3365_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.polySurface3278_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.polySurface3289_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.polySurface3199_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.polySurface3196_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.polySurface3200_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.polySurface3183_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.polySurface3197_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.polySurface3791_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.polySurface3798_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.polySurface3796_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.polySurface3789_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.polySurface3790_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.polySurface3805_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.polySurface3944_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.polySurface4037_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.polySurface3803_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.polySurface3804_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.polySurface1360_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.polySurface1362_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.polySurface1345_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.polySurface1359_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.polySurface4061_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.polySurface4891_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.polySurface4874_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.polySurface3779_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.polySurface3780_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.polySurface3781_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.polySurface1331_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.polySurface1332_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.polySurface5775_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.pTorus11_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.pTorus12_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.pTorus9_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.polySurface5780_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.pasted__polySurface3470_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.pPlane97_envi_texture_0.geometry}
        material={materials.envi_texture}
      />
      <mesh
        
        
        geometry={nodes.polySurface5388_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.polySurface5384_envi_texture_0.geometry}
        material={materials.envi_texture}
      />
      <mesh
        
        
        geometry={nodes.polySurface5380_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.polySurface5675_envi_texture_0.geometry}
        material={materials.envi_texture}
      />
      <mesh
        
        
        geometry={nodes.polySurface5709_envi_texture_0.geometry}
        material={materials.envi_texture}
      />
      <mesh
        
        
        geometry={nodes.pTorus8_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.pTorus7_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.polySurface5583_envi_texture_0.geometry}
        material={materials.envi_texture}
      />
      <mesh
        
        
        geometry={nodes.pTorus10_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.polySurface5269_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.polySurface5379_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.polySurface5779_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
      <mesh
        
        
        geometry={nodes.polySurface5781_TEXTURE_0.geometry}
        material={materials.TEXTURE}
      />
    </a.group>
  );
}


export default Island;
